name: steam
version: '1.0.0.85'
summary: Launcher for the Steam software distribution service
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
adopt-info: steam
grade: stable
confinement: strict
base: core24
platforms:
  arm64:
    build-on: [arm64]
    build-for: [arm64]
compression: lzo
assumes:
  - snapd2.62

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

package-repositories:
  - type: apt
    url: http://ports.ubuntu.com/ubuntu-ports/
    suites: [noble, noble-updates]
    components: [main, universe]
    architectures: [arm64]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
  - type: apt
    ppa: fex-emu/fex

layout:
  # https://discourse.ubuntu.com/t/the-graphics-core20-snap-interface/23000
  /usr/share/drirc.d:
    bind: $SNAP/graphics/usr/share/drirc.d
  /usr/share/glvnd/egl_vendor.d:
    bind: $SNAP/graphics/usr/share/glvnd/egl_vendor.d
  # DRI drivers
  /usr/lib/aarch64-linux-gnu/dri:
    bind: $SNAP/graphics/usr/lib/aarch64-linux-gnu/dri
  # GBM
  /usr/lib/aarch64-linux-gnu/gbm:
    bind: $SNAP/graphics/usr/lib/aarch64-linux-gnu/gbm
  # VDPAU drivers
  /usr/lib/aarch64-linux-gnu/vdpau:
    bind: $SNAP/graphics/usr/lib/aarch64-linux-gnu/vdpau
  # Library files
  /usr/lib/aarch64-linux-gnu/libdecor-0.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdecor-0.so.0.200.2
  /usr/lib/aarch64-linux-gnu/libdecor-0.so.0.200.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdecor-0.so.0.200.2
  /usr/lib/aarch64-linux-gnu/libdrm_amdgpu.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdrm_amdgpu.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libdrm_amdgpu.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdrm_amdgpu.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libdrm.so.2:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdrm.so.2.4.0
  /usr/lib/aarch64-linux-gnu/libdrm.so.2.4.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libdrm.so.2.4.0
  /usr/lib/aarch64-linux-gnu/libEGL_mesa.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libEGL_mesa.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libEGL_mesa.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libEGL_mesa.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libEGL.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libEGL.so.1.1.0
  /usr/lib/aarch64-linux-gnu/libEGL.so.1.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libEGL.so.1.1.0
  /usr/lib/aarch64-linux-gnu/libgallium-25.3.3 - kisak-mesa PPA.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libgallium-25.3.3 - kisak-mesa PPA.so
  /usr/lib/aarch64-linux-gnu/libgbm.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libgbm.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libgbm.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libgbm.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libGLdispatch.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libGLdispatch.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libGLESv2.so.2:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLESv2.so.2.1.0
  /usr/lib/aarch64-linux-gnu/libGLESv2.so.2.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLESv2.so.2.1.0
  /usr/lib/aarch64-linux-gnu/libGL.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGL.so.1.7.0
  /usr/lib/aarch64-linux-gnu/libGL.so.1.7.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGL.so.1.7.0
  /usr/lib/aarch64-linux-gnu/libGLX_indirect.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0
  /usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLX_mesa.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libGLX.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLX.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libGLX.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libGLX.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libicudata.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicudata.so.74.2
  /usr/lib/aarch64-linux-gnu/libicudata.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicudata.so.74.2
  /usr/lib/aarch64-linux-gnu/libicui18n.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicui18n.so.74.2
  /usr/lib/aarch64-linux-gnu/libicui18n.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicui18n.so.74.2
  /usr/lib/aarch64-linux-gnu/libicuio.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicuio.so.74.2
  /usr/lib/aarch64-linux-gnu/libicuio.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicuio.so.74.2
  /usr/lib/aarch64-linux-gnu/libicutest.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicutest.so.74.2
  /usr/lib/aarch64-linux-gnu/libicutest.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicutest.so.74.2
  /usr/lib/aarch64-linux-gnu/libicutu.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicutu.so.74.2
  /usr/lib/aarch64-linux-gnu/libicutu.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicutu.so.74.2
  /usr/lib/aarch64-linux-gnu/libicuuc.so.74:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicuuc.so.74.2
  /usr/lib/aarch64-linux-gnu/libicuuc.so.74.2:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libicuuc.so.74.2
  /usr/lib/aarch64-linux-gnu/libLLVM-20.so:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libLLVM.so.20.1
  /usr/lib/aarch64-linux-gnu/libLLVM.so.20.1:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libLLVM.so.20.1
  /usr/lib/aarch64-linux-gnu/libsensors.so.5:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libsensors.so.5.0.0
  /usr/lib/aarch64-linux-gnu/libsensors.so.5.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libsensors.so.5.0.0
  /usr/lib/aarch64-linux-gnu/libspirv_to_dxil.a:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libspirv_to_dxil.a
  /usr/lib/aarch64-linux-gnu/libspirv_to_dxil.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libspirv_to_dxil.so
  /usr/lib/aarch64-linux-gnu/libstdc++.so.6:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.33
  /usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.33:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.33
  /usr/lib/aarch64-linux-gnu/libva.so.2:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libva.so.2.2000.0
  /usr/lib/aarch64-linux-gnu/libva.so.2.2000.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libva.so.2.2000.0
  /usr/lib/aarch64-linux-gnu/libva-x11.so.2:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libva-x11.so.2.2000.0
  /usr/lib/aarch64-linux-gnu/libva-x11.so.2.2000.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libva-x11.so.2.2000.0
  /usr/lib/aarch64-linux-gnu/libvdpau.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvdpau.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libvdpau.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvdpau.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libvkd3d-shader.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvkd3d-shader.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libvkd3d-shader.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvkd3d-shader.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libvkd3d.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvkd3d.so.1.2.0
  /usr/lib/aarch64-linux-gnu/libvkd3d.so.1.2.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvkd3d.so.1.2.0
  /usr/lib/aarch64-linux-gnu/libVkLayer_INTEL_nullhw.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libVkLayer_INTEL_nullhw.so
  /usr/lib/aarch64-linux-gnu/libVkLayer_MESA_anti_lag.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libVkLayer_MESA_anti_lag.so
  /usr/lib/aarch64-linux-gnu/libVkLayer_MESA_device_select.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libVkLayer_MESA_device_select.so
  /usr/lib/aarch64-linux-gnu/libVkLayer_MESA_overlay.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libVkLayer_MESA_overlay.so
  /usr/lib/aarch64-linux-gnu/libVkLayer_MESA_screenshot.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libVkLayer_MESA_screenshot.so
  /usr/lib/aarch64-linux-gnu/libvulkan_asahi.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_asahi.so
  /usr/lib/aarch64-linux-gnu/libvulkan_broadcom.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_broadcom.so
  /usr/lib/aarch64-linux-gnu/libvulkan_dzn.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_dzn.so
  /usr/lib/aarch64-linux-gnu/libvulkan_freedreno.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_freedreno.so
  /usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_gfxstream.so
  /usr/lib/aarch64-linux-gnu/libvulkan_intel.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_intel.so
  /usr/lib/aarch64-linux-gnu/libvulkan_lvp.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_lvp.so
  /usr/lib/aarch64-linux-gnu/libvulkan_nouveau.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_nouveau.so
  /usr/lib/aarch64-linux-gnu/libvulkan_panfrost.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_panfrost.so
  /usr/lib/aarch64-linux-gnu/libvulkan_radeon.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_radeon.so
  /usr/lib/aarch64-linux-gnu/libvulkan.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan.so.1.3.275
  /usr/lib/aarch64-linux-gnu/libvulkan.so.1.3.275:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan.so.1.3.275
  /usr/lib/aarch64-linux-gnu/libvulkan_virtio.so:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libvulkan_virtio.so
  /usr/lib/aarch64-linux-gnu/libwayland-client.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libwayland-client.so.0.22.0
  /usr/lib/aarch64-linux-gnu/libwayland-client.so.0.22.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libwayland-client.so.0.22.0
  /usr/lib/aarch64-linux-gnu/libwayland-egl.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libwayland-egl.so.1.22.0
  /usr/lib/aarch64-linux-gnu/libwayland-egl.so.1.22.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libwayland-egl.so.1.22.0
  /usr/lib/aarch64-linux-gnu/libX11.so.6:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libX11.so.6.4.0
  /usr/lib/aarch64-linux-gnu/libX11.so.6.4.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libX11.so.6.4.0
  /usr/lib/aarch64-linux-gnu/libX11-xcb.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libX11-xcb.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libX11-xcb.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libX11-xcb.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libXau.so.6:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXau.so.6.0.0
  /usr/lib/aarch64-linux-gnu/libXau.so.6.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXau.so.6.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-dri3.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-dri3.so.0.1.0
  /usr/lib/aarch64-linux-gnu/libxcb-dri3.so.0.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-dri3.so.0.1.0
  /usr/lib/aarch64-linux-gnu/libxcb-glx.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-glx.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-glx.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-glx.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-present.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-present.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-present.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-present.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-randr.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-randr.so.0.1.0
  /usr/lib/aarch64-linux-gnu/libxcb-randr.so.0.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-randr.so.0.1.0
  /usr/lib/aarch64-linux-gnu/libxcb-shm.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-shm.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-shm.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-shm.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/aarch64-linux-gnu/libxcb.so.1.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/aarch64-linux-gnu/libxcb-sync.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-sync.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-sync.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-sync.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-xfixes.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-xfixes.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-xfixes.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-xfixes.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-xkb.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-xkb.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libxcb-xkb.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxcb-xkb.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libXdmcp.so.6:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXdmcp.so.6.0.0
  /usr/lib/aarch64-linux-gnu/libXdmcp.so.6.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXdmcp.so.6.0.0
  /usr/lib/aarch64-linux-gnu/libXext.so.6:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXext.so.6.4.0
  /usr/lib/aarch64-linux-gnu/libXext.so.6.4.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXext.so.6.4.0
  /usr/lib/aarch64-linux-gnu/libXfixes.so.3:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXfixes.so.3.1.0
  /usr/lib/aarch64-linux-gnu/libXfixes.so.3.1.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXfixes.so.3.1.0
  /usr/lib/aarch64-linux-gnu/libxkbcommon-x11.so.0:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxkbcommon-x11.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxkbcommon-x11.so.0.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxkbcommon-x11.so.0.0.0
  /usr/lib/aarch64-linux-gnu/libxml2.so.2:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxml2.so.2.9.14
  /usr/lib/aarch64-linux-gnu/libxml2.so.2.9.14:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxml2.so.2.9.14
  /usr/lib/aarch64-linux-gnu/libxshmfence.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxshmfence.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libxshmfence.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libxshmfence.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libXxf86vm.so.1:
    symlink: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXxf86vm.so.1.0.0
  /usr/lib/aarch64-linux-gnu/libXxf86vm.so.1.0.0:
    bind-file: $SNAP/graphics/usr/lib/aarch64-linux-gnu/libXxf86vm.so.1.0.0
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /etc/fonts:
    bind: $SNAP/etc/fonts

plugs:
  gaming-graphics-core24:
    interface: content
    target: $SNAP/graphics
    default-provider: gaming-graphics-core24
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  dot-local-share-steam:
    interface: personal-files
    write:
      - $HOME/.local/share/Steam
      - $HOME/Steam
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  dot-local-share-icons:
    interface: personal-files
    write:
      - $HOME/.local/share/icons
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true

slots:
  steam:
    interface: dbus
    bus: session
    name: com.steampowered.PressureVessel.LaunchAlongsideSteam

hooks:
  configure:
    plugs:
      - opengl

parts:
  gaming-graphics-core24:
    plugin: nil
    build-snaps:
      - gaming-graphics-core24
  amd64-content:
    plugin: dump
    source: https://github.com/MitchellAugustin/steam-snap/releases/download/amd64-components-12-16-25.2/steam_231_amd64.tar.gz
    stage:
      - -usr/bin/curl
      - -usr/bin/fc-cache
      - -usr/bin/fc-cat
      - -usr/bin/fc-conflist
      - -usr/bin/fc-list
      - -usr/bin/fc-match
      - -usr/bin/fc-pattern
      - -usr/bin/fc-query
      - -usr/bin/fc-scan
      - -usr/bin/fc-validate
      - -usr/bin/gtk-update-icon-cache
      - -usr/bin/update-mime-database
      - -usr/bin/zenity
      - -usr/libexec/dconf-service
      - -usr/share/doc/libcups2t64/changelog.Debian.gz
      - -bin/desktop-launch
    organize:
        steam_231_amd64: .
  amd64-rootfs:
    plugin: dump
    source: https://github.com/MitchellAugustin/steam-snap/releases/download/amd64-components-12-16-25.2/amd64_rootfs.tar.gz
    organize:
        amd64_rootfs: .
  fex-emu:
    plugin: nil
    stage-packages:
      - fex-emu-armv8.0
      - fex-emu-wine
      - zenity
  fex-config:
    plugin: dump
    source: ./fex_config
  wget:
    plugin: nil
    stage-packages:
      - wget
  desktop-launch:
    plugin: dump
    source: ./src/
    organize:
        desktop-launch: bin/
    stage:
      - bin/desktop-launch

  
apps:
  steam:
    command: usr/bin/fex_launcher.sh
    plugs:
      - shmem
      - desktop
      - desktop-legacy
      - wayland
      - home
      - x11
      - gsettings
      - hardware-observe
      - mount-observe
      - system-observe
      - network-observe
      - joystick
      - network
      - network-bind
      - opengl
      - audio-playback
      - audio-record
      - screen-inhibit-control
      - process-control
      - bluez
      - network-control
      - fuse-support
      - steam-support
      - removable-media
      - upower-observe
      - uinput
      - dot-local-share-steam
